// Mocks generated by Mockito 5.4.6 from annotations
// in test_login/test/features/ai_assistant/integration/ai_assistant_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:test_login/features/ai_assistant/domain/entities/assistant_message.dart'
    as _i5;
import 'package:test_login/features/ai_assistant/domain/repositories/ai_assistant_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AiAssistantRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiAssistantRepository extends _i1.Mock
    implements _i3.AiAssistantRepository {
  MockAiAssistantRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i3.AiFailure, _i5.AssistantMessage>> sendMessage({
    required String? prompt,
    required List<_i5.AssistantMessage>? history,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #prompt: prompt,
              #history: history,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i3.AiFailure, _i5.AssistantMessage>
                >.value(
                  _FakeEither_0<_i3.AiFailure, _i5.AssistantMessage>(
                    this,
                    Invocation.method(#sendMessage, [], {
                      #prompt: prompt,
                      #history: history,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i3.AiFailure, _i5.AssistantMessage>>);
}
